CREATE TABLE IF NOT EXISTS Categories (
  name VARCHAR(200) NOT NULL UNIQUE,
  id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Products (
  id VARCHAR(200) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  price DECIMAL(6,2) NOT NULL,
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES Categorias (id)
);